apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: vpro-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"   # enable regex path matching. This helps in complex path matching scenarios.
spec:
  ingressClassName: nginx
  rules:
  - host: vprofilejpj.jpjdevops.info # replace with your domain name
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vproapp-service # name of the service created for the application
            port:
              number: 8080

